name: CI

on: [push, pull_request]

jobs:
  assemble:
    name: Assemble

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Assemble project
        run: ./gradlew assemble
  style:
    name: Check formatting

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Check formatting
        run: ./gradlew spotlessCheck
  javadoc:
    name: Publish Javadoc

    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    needs: [assemble]

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Build
        run: ./gradlew build
      - name: Publish Javadoc to Netlify
        run: npx netlify-cli deploy --prod --dir lib/build/docs/javadoc
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
  docs:
    name: Build docs

    runs-on: ubuntu-latest

    timeout-minutes: 5

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        # Required due to a limitation in setup-node https://github.com/actions/setup-node/issues/480#issuecomment-1820622085
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: "yarn"
          cache-dependency-path: web/yarn.lock
      - name: cd to docs directory
        run: cd web
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build docs
        run: yarn build
